# Generated by Django 6.0 on 2025-12-24 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: 📚, 🧮, 🔬)", max_length=50)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('chapitre', models.CharField(blank=True, max_length=200)),
                ('contenu_original', models.TextField(help_text="Contenu brut saisi par l'élève")),
                ('type_saisie', models.CharField(choices=[('manuel', 'Saisie manuelle'), ('photo', 'Photo du cahier'), ('copie', 'Copier-coller')], max_length=20)),
                ('photo_cours', models.ImageField(blank=True, null=True, upload_to='cours_photos/')),
                ('contenu_traite', models.TextField(blank=True, help_text="Cours réorganisé par l'IA")),
                ('resume', models.TextField(blank=True, help_text="Résumé généré par l'IA")),
                ('fiche_revision', models.TextField(blank=True, help_text='Fiche de révision')),
                ('exemples', models.TextField(blank=True, help_text='Exemples et exercices')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_traitement', 'En traitement'), ('traite', 'Traité'), ('erreur', 'Erreur')], default='brouillon', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nombre_revisions', models.IntegerField(default=0)),
                ('derniere_revision', models.DateTimeField(blank=True, null=True)),
                ('favori', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='courses.matiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai/Faux'), ('ouverte', 'Question ouverte'), ('exercice', 'Exercice')], max_length=20)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('enonce', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('reponse_correcte', models.TextField()),
                ('explication', models.TextField(blank=True, help_text='Explication de la réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fois_posee', models.IntegerField(default=0)),
                ('fois_reussie', models.IntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.cours')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['difficulte', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.TextField()),
                ('est_correcte', models.BooleanField()),
                ('temps_reponse', models.IntegerField(blank=True, help_text='Temps en secondes', null=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_eleves', to='courses.question')),
            ],
            options={
                'verbose_name': 'Réponse élève',
                'verbose_name_plural': 'Réponses élèves',
                'ordering': ['-date_reponse'],
            },
        ),
    ]
