# Generated by Django 6.0 on 2025-12-25 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_exercice', models.CharField(choices=[('maths', 'Mathématiques'), ('physique', 'Physique-Chimie'), ('francais', 'Français'), ('autres', 'Autres')], default='autres', max_length=20)),
                ('enonce', models.TextField(help_text="L'énoncé de l'exercice")),
                ('photo_exercice', models.ImageField(blank=True, help_text="Photo de l'exercice", null=True, upload_to='exercices/')),
                ('tentative_eleve', models.TextField(blank=True, help_text='Ta tentative de résolution')),
                ('explication_ia', models.TextField(blank=True, help_text="Explication détaillée par l'IA")),
                ('solution_complete', models.TextField(blank=True, help_text='Solution complète')),
                ('conseils', models.TextField(blank=True, help_text='Conseils pour progresser')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('utile', models.BooleanField(default=False, help_text="L'élève a trouvé l'aide utile")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='courses.matiere')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_eleve', models.TextField()),
                ('reponse_ia', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='courses.exercice')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['date_message'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=2)),
                ('niveau', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre dans l'année scolaire")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='courses.matiere')),
            ],
            options={
                'verbose_name': 'Programme scolaire',
                'verbose_name_plural': 'Programmes scolaires',
                'ordering': ['pays', 'classe', 'matiere', 'ordre'],
                'unique_together': {('pays', 'classe', 'serie', 'matiere', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='CoursGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_automatiquement', models.BooleanField(default=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cours_genere', to='courses.cours')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_generes', to='courses.programmescolaire')),
            ],
            options={
                'verbose_name': 'Cours généré',
                'verbose_name_plural': 'Cours générés',
            },
        ),
    ]
