# Generated by Django 6.0 on 2025-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serie',
            field=models.CharField(blank=True, choices=[('A', 'Série A (Littéraire)'), ('C', 'Série C (Scientifique)'), ('D', 'Série D (Sciences expérimentales)'), ('E', 'Série E (Mathématiques et Techniques)'), ('G', 'Série G (Techniques administratives)'), ('F', 'Série F (Techniques industrielles)')], help_text='Pour le lycée uniquement', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('GN', 'Guinée')], max_length=2),
        ),
    ]
